name: MovieLens API - Docker
values:
  - key: baseUrl
    value: 'http://localhost:8000'
    description: Docker container URL
  - key: baseUrlLocal
    value: 'http://localhost:8000'
    description: Local development URL
  - key: defaultUserId
    value: '42'
  - key: defaultMovieId
    value: '318'
  - key: shawsankRedemption
    value: '318'
    description: The Shawshank Redemption
  - key: toyStory
    value: '1'
    description: Toy Story
